# Generated by Django 3.1.7 on 2021-04-23 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210422_0436'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('state', models.BooleanField(default=True)),
                ('create_to', models.DateTimeField(auto_now_add=True)),
                ('update_to', models.DateTimeField(auto_now=True)),
                ('test_type', models.CharField(choices=[('1', 'Theoretical'), ('2', 'Practical')], max_length=15)),
                ('name', models.CharField(max_length=200)),
                ('ci', models.CharField(max_length=15)),
                ('time_available', models.CharField(max_length=50)),
                ('qty_lesson', models.PositiveIntegerField(default=0)),
                ('phone', models.CharField(max_length=11)),
                ('email', models.EmailField(max_length=254)),
                ('trainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web.teacher')),
            ],
            options={
                'verbose_name': 'TestRequest',
                'verbose_name_plural': 'TestsRequest',
            },
        ),
    ]
