# Generated by Django 3.1.7 on 2021-04-23 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_testrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testrequest',
            name='test_type',
            field=models.CharField(choices=[('1', 'Teórico'), ('2', 'Práctico')], max_length=1),
        ),
    ]
